### ISSUE TITLE
Access denied when trying to setup this plugin

### ISSUE THREAD

**Issue by com2ghz** [polychrom/cordova-android-accountmanager#9]
Hey, I would like to use this plugin in my cordova app to sync contacts. I have followed the steps as you described.

This is the javascript error I get by just executing the code 'addAccountExplicitly':
````javascript
processMessage failed: Message: F09 AccountManager395665399 sAccess denied cordova.js:1034
processMessage failed: Error: TypeError: Cannot read property '_index' of undefined cordova.js:1035
processMessage failed: Stack: TypeError: Cannot read property '_index' of undefined
    at AccountManager.getPassword (file:///android_asset/www/plugins/com.polychrom.cordova.AccountManagerPlugin/www/js/accountmanager.js:77:44)
    at http://domain.tld:9001/js/controllers.js:308:9
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:294:48)
    at processMessage (file:///android_asset/www/cordova.js:1029:21)
    at Function.androidExec.processMessages (file:///android_asset/www/cordova.js:1063:13)
    at Object.androidExec [as exec] (file:///android_asset/www/cordova.js:922:25)
    at AccountManager.addAccountExplicitly (file:///android_asset/www/plugins/com.polychrom.cordova.AccountManagerPlugin/www/js/accountmanager.js:18:17)
    at new <anonymous> (http://domain.tld:9001/js/controllers.js:293:5)
    at invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11994:17)
    at Object.instantiate (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:12002:27) 
````

Did I forget something? Authenticator.xml is also under res/xml like you describe.

**Comment by com2ghz** [comment]
Fixed by using the example code in the Example folder. The documentation in the Readme is incorrect.
